### ISSUE TITLE
HTML5将死

### ISSUE THREAD

**Issue by miniflycn** [miniflycn/Ques#30]
> 去年开始来有个热门职位叫“HTML5开发工程师”，移动浪潮炒起了iOS和Android开发工程师，也炒起了“HTML5开发工程师”。咳咳，当然在我们前端看来这是个很滑稽的职位……这不就是前端吗？但是随着React-native的春风，HTML5的`部署灵活`，`承载内容`、`引流冲量`、`方案试错`、`快速迭代`、`外部对接`、`开源`等优势可能就此不复存在。

### HTML5替代方案

实际上腾讯内部也在探索一种替代HTML5的方案，并在性能下得以解决。在iOS手Q引入lua，通过更新脚本来动态运营一些重要的运营位（例如附近的群）。

但这一方案并没有对HTML5造成实际的威胁，由于不通用，其只能由特定的iOS开发人员开发。无法大规模推广利用。

### React-native解决了什么？

* 迭代速度，服务器更新脚本立刻能反应在界面上，不需要走App Store繁琐的审查逻辑，以及版本碎片化导致的痛楚
* 性能，屏蔽WebView，用原生控件替代，彻底解决了被诟病的`WebView创建速度问题`、`DOM渲染性能问题`、`Javascript单线程问题`
* 比Hybrid更容易在体验上向Native靠齐，Android 5.0开始将使用[Material Design](http://design.1sters.com/)来规范设计体验，前端想达到这种体验的几乎难以登天，但React-native却至少存在可能性
* 比Ajax更好的数据获取方式，React-native可通过TCP来获取数据，但Web只能通过HTTP1.1
* 较平滑的学习曲线，可以很快上手并制作成品
* 比Canvas UI更友好，比如什么无障碍化，链接跳转，Canvas UI基本做不了，但Native没什么难度

**Comment by webryan** [comment]
不够准确。 主流web前端开发工程师的技能将逐步转到HTML5战场， hybrid部分的前端工程师将兼备类react-native的跨端研发能力。 我们只是都向前走了一大步而已。

**Comment by miniflycn** [comment]
主要指APP内的HTML5啦，Web前端还是有市场，但是是在明确让用户感觉到就是Web的地方。
