### ISSUE TITLE
throw errnoException(err, 'kill');

### ISSUE THREAD

**Issue by leiming** [miniflycn/Ques#47]
在 D2 与 master 分支，node v0.12.9  与 v4.2.2 后，运行任意 gulp 指令均报如下错误：

```
$ gulp learn
[21:21:30] Using gulpfile ~/IdeaProjects/D2/Ques/gulpfile.js
[21:21:30] Starting 'learn'...
app close
node.js:776
        throw errnoException(err, 'kill');
        ^

Error: kill ESRCH
    at exports._errnoException (util.js:874:11)
    at process.kill (node.js:776:15)
    at process.<anonymous> (/Users/leiming/IdeaProjects/D2/Ques/gulpfile.js:155:13)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
```

**Comment by miniflycn** [comment]
谢谢关注，明天我回深圳看看是什么问题，目前还在杭州聚友，身上没有电脑，不好意思，请原谅

**Comment by jsrider** [comment]
同上问题，求解答

**Comment by miniflycn** [comment]
简单解决方案，运行相同效果的命令：
node app -p 3000 -a learn
看看错误是什么。

ps：我记忆中的原因是cssgrace在去d2之前被我删了，但是代码依赖可能还在。解决办法是：

npm install cssgrace就可以了

**Comment by leiming** [comment]
谢谢回复，确实运行  

```
npm install cssgrace --save-dev
```

后，node server 可以正常启动，不过此时静态文件的目录指向不对：

![image](https://cloud.githubusercontent.com/assets/2059859/11936975/654f42e6-a84c-11e5-9ab0-d5c735b6c7e2.png)

已经无伤大雅了。

**Comment by miniflycn** [comment]
因为learn模块是临时做给d2演示用的的，有点点小问题。这里应该直接打开：http://localhost:3000/learn/

mac里面有两个快捷键可用cmd+o，打开文件。cmd+s，保存文件

**Comment by miniflycn** [comment]
建议直接使用http://localhost:3000/1.html类似这种方式查看页面，thx

**Comment by jsrider** [comment]
D2 分享的 PPT 能给一下吗？我们想对团队做个二次分享

**Comment by miniflycn** [comment]
今天晚上我发一个到icloud吧

**Comment by jsrider** [comment]
好的，到时候 附上一个下载链接啊，也可以 邮件我哈， shaowei.xusw@alibaba-inc.com 感激不尽~

**Comment by miniflycn** [comment]
https://www.icloud.com/keynote/000upQh9RugD05UD8GSNNsKRw#Component%E5%8C%96%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E8%B7%B5

**Comment by leiming** [comment]
请问如何定义或引用默认样式文件？

![image](https://cloud.githubusercontent.com/assets/2059859/11992808/2b828562-aa65-11e5-8311-7cf067ad22e0.png)

似乎不在默认的 `test.html` iframe 中：

![image](https://cloud.githubusercontent.com/assets/2059859/11992782/ef2e90f6-aa64-11e5-95de-095e8ac25c1b.png)

**Comment by miniflycn** [comment]
@leiming 你这个好奇怪啊。我没看懂为什么。你把src/components/ui/button给删了么？

**Comment by leiming** [comment]
@miniflycn 我说下复现步骤：master 分支上运行 ` gulp learn`, 访问：

http://localhost:3000/learn/index.html

![image](https://cloud.githubusercontent.com/assets/2059859/11993000/68f42430-aa67-11e5-9fea-8867cef57380.png)

不知为何，默认的 css 没有注入，可能和 learn 的环境有关。

**Comment by miniflycn** [comment]
@leiming 

使用链接：

http://localhost:3000/learn/

这个模块是用于演示的，所以没有写的很好，抱歉。

**Comment by miniflycn** [comment]
哦，我知道了，请把<ui-button>放在body里面= =

**Comment by leiming** [comment]
@miniflycn 麻烦您把修复步骤稍微说详细一些，比如【把XX 放在 YYY 的 body里面】。

如果彻底修复好了，我是很愿意给 PR 的~

**Comment by miniflycn** [comment]
@leiming 

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<ui-button>hello world</ui-button>
</body>
</html>
```

就是按照这个填一下。说白就是按照正常的html5一般有的东西。

**Comment by leiming** [comment]
@miniflycn 谢谢，这么写确实可用，访问：

http://localhost:3000/learn/index.html 没有问题

![image](https://cloud.githubusercontent.com/assets/2059859/11993244/b7ec615e-aa69-11e5-936b-200e68b5318e.png)

不过：

http://localhost:3000/learn/

![image](https://cloud.githubusercontent.com/assets/2059859/11993262/ced61a54-aa69-11e5-826e-51d95b2f3a22.png)

这个我已经在 https://github.com/miniflycn/Ques/issues/47#issuecomment-166369289 中提过了，您说的【mac里面有两个快捷键可用cmd+o，打开文件。cmd+s，保存文件】这个修复步骤，和 node server 的静态文件引用的有什么关系，我不是很明白。

**Comment by miniflycn** [comment]
@leiming 

不是，就是在用：

http://localhost:3000/learn/

不是:

http://localhost:3000/learn

注意上面一个是对的。这两个路径写相对依赖会指向不同的地方，导致出现问题。当然最合适的是服务器重定向一下。这是我的锅

**Comment by leiming** [comment]
https://github.com/miniflycn/Ques/pull/48
